# Generated by Django 5.2.6 on 2025-09-05 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, unique=True)),
                ('energia_kcal', models.FloatField(help_text='Calorias por 100g')),
                ('carboidratos_g', models.FloatField(help_text='Carboidratos (g) por 100g')),
                ('proteinas_g', models.FloatField(help_text='Proteínas (g) por 100g')),
                ('lipideos_g', models.FloatField(help_text='Lipídios (g) por 100g')),
                ('fibra_g', models.FloatField(blank=True, help_text='Fibras (g) por 100g', null=True)),
                ('sodio_mg', models.FloatField(blank=True, help_text='Sódio (mg) por 100g', null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Refeicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RefeicaoAlimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_g', models.FloatField(help_text='Quantidade em gramas')),
                ('alimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.alimento')),
                ('refeicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='api.refeicao')),
            ],
        ),
    ]
