# Generated by Django 5.2.6 on 2025-09-07 13:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20250905_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='refeicaoalimento',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='refeicaoalimento',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 9, 7, 0, 0)),
            preserve_default=False,
        ),
    ]
