# Generated by Django 5.2.6 on 2025-09-07 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_refeicaoalimento_data_atualizacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='refeicao',
            name='essencial',
            field=models.BooleanField(default=False),
        ),
    ]
