# Generated by Django 5.2.6 on 2025-09-05 20:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idade', models.IntegerField()),
                ('peso', models.FloatField(help_text='Peso em kg')),
                ('altura', models.FloatField(help_text='Altura em cm')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1)),
                ('nivel_atividade', models.CharField(choices=[('sedentario', 'Sedentário'), ('leve', 'Levemente ativo (1-3x/semana)'), ('moderado', 'Moderadamente ativo (3-5x/semana)'), ('alto', 'Muito ativo (6-7x/semana)'), ('extremo', 'Extremamente ativo (atleta)')], max_length=20)),
                ('objetivo', models.CharField(choices=[('emagrecer', 'Emagrecer'), ('manter', 'Manter peso'), ('ganhar', 'Ganhar peso')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlanoAlimentar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calorias_diarias', models.IntegerField()),
                ('proteinas_diarias', models.FloatField(help_text='Proteínas em gramas')),
                ('carboidratos_diarios', models.FloatField(help_text='Carboidratos em gramas')),
                ('gorduras_diarias', models.FloatField(help_text='Gorduras em gramas')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plano_alimentar', to='user.userprofile')),
            ],
        ),
    ]
