# Generated by Django 5.2.6 on 2025-09-05 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userprofile_planoalimentar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='altura',
            field=models.FloatField(blank=True, help_text='Altura em cm', null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='idade',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='nivel_atividade',
            field=models.CharField(blank=True, choices=[('sedentario', 'Sedentário'), ('leve', 'Levemente ativo (1-3x/semana)'), ('moderado', 'Moderadamente ativo (3-5x/semana)'), ('alto', 'Muito ativo (6-7x/semana)'), ('extremo', 'Extremamente ativo (atleta)')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='objetivo',
            field=models.CharField(blank=True, choices=[('emagrecer', 'Emagrecer'), ('manter', 'Manter peso'), ('ganhar', 'Ganhar peso')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='peso',
            field=models.FloatField(blank=True, help_text='Peso em kg', null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1, null=True),
        ),
    ]
