# Generated by Django 5.2.6 on 2025-09-06 15:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(default='gpt-3.5-turbo', max_length=50)),
                ('max_tokens', models.IntegerField(default=500)),
                ('temperature', models.FloatField(default=0.7)),
                ('system_prompt', models.TextField(default='\n        Você é um assistente nutricional especializado e amigável do NutriApp.\n        Suas principais funções são:\n        1. Responder dúvidas sobre nutrição de forma clara e educativa\n        2. Sugerir substituições de alimentos baseadas no perfil do usuário\n        3. Explicar valores nutricionais e benefícios dos alimentos\n        4. Dar orientações personalizadas considerando objetivos\n        (emagrecer, ganhar peso, manter)\n        5. Sempre orientar a procurar um nutricionista para casos específicos\n\n        Mantenha suas respostas:\n        - Claras e objetivas\n        - Baseadas em evidências científicas\n        - Personalizadas quando possível\n        - Sempre incentivando hábitos saudáveis\n        - Nunca substitua consulta médica ou nutricional profissional\n            ')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração do Chatbot',
                'verbose_name_plural': 'Configurações do Chatbot',
            },
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Nova Conversa', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Usuário'), ('assistant', 'Assistente'), ('system', 'Sistema')], max_length=10)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('tokens_used', models.IntegerField(blank=True, null=True)),
                ('response_time', models.FloatField(blank=True, help_text='Tempo de resposta em segundos', null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chatbot.chatsession')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
