# Generated by Django 5.2.6 on 2025-09-06 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbotconfig',
            name='model_name',
            field=models.CharField(default='llama-3.1-8b-instant', max_length=50),
        ),
    ]
